//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingwithEntityframwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pd_product
    {
        public string PD_ID { get; set; }
        public string PD_NAME { get; set; }
        public Nullable<decimal> PD_VALUE { get; set; }
        public Nullable<decimal> PD_PRICE { get; set; }
        public string TP_ID { get; set; }
        public string PD_UNIT { get; set; }
    }
}
